spring:
  datasource:
    url: jdbc:mysql://${dbUrl}:${dbPort}/${dbName}?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: ${dbUsername}
    password: ${dbPassword}
    driverClassName: com.mysql.cj.jdbc.Driver
  #jpa 测试
  jpa:
    hibernate:
      ddl-auto: update # 新增数据库链接必须的参数
    # 控制台显示SQL
    show-sql: true
    properties:
      hibernate.format_sql: true
  #Springboot2.6以后将SpringMVC 默认路径匹配策略从AntPathMatcher 更改为PathPatternParser，导致出错
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER